module.exports = {
  // Client → Server
  AUTH: 'AUTH',
  MESSAGE: 'MESSAGE',
  JOIN_RESPONSE: 'JOIN_RESPONSE',
  ACK: 'ACK',
  KEY_DISTRIBUTION: 'KEY_DISTRIBUTION',
  PING: 'PING',

  // Server → Client
  AUTH_FAILED: 'AUTH_FAILED',
  PONG: 'PONG',
  MESSAGE_OUT: 'MESSAGE',
  JOIN_REQUEST: 'JOIN_REQUEST',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  JOIN_REQUEST_RESOLVED: 'JOIN_REQUEST_RESOLVED',
  REQUESTS_LOCK_CHANGED: 'REQUESTS_LOCK_CHANGED',
  DELIVERED: 'DELIVERED',
  UNDELIVERED: 'UNDELIVERED',
};
