module.exports = {
  // Client → Server
  AUTH: 'AUTH',
  MESSAGE: 'MESSAGE',
  JOIN_RESPONSE: 'JOIN_RESPONSE',
  PING: 'PING',

  // Server → Client
  AUTH_FAILED: 'AUTH_FAILED',
  PONG: 'PONG',
  MESSAGE_OUT: 'MESSAGE',
  JOIN_REQUEST: 'JOIN_REQUEST',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  JOIN_REQUEST_RESOLVED: 'JOIN_REQUEST_RESOLVED',
};
